### ISSUE TITLE
App crashes on search

### ISSUE THREAD

**Issue by Asuka-pr8** [abhishekabhi789/LyricsForPowerAmp#11]
App crashes in coarse search and fine search if not all three fields are filled

OS:android 13
Device: Poco x5 pro

**Comment by abhishekabhi789** [comment]
I couldn't reproduce this issue.
Is it reproducible for you? Or just happened once?
Could you provide me with each field's value and search mode when the crash occurred?

**Comment by Asuka-pr8** [comment]
Searching anything that could have a result does it for me

I can make an adb log file if that could help

**Comment by abhishekabhi789** [comment]
That'll be very helpful.

**Comment by Asuka-pr8** [comment]
[crash-io-github-abhishekabhi789-lyricsforpoweramp-15_10-17-05-21_373.zip](https://github.com/user-attachments/files/17380713/crash-io-github-abhishekabhi789-lyricsforpoweramp-15_10-17-05-21_373.zip)
Ok so I did this using logfox and shizuku
Ut detected the crash and here is what it gave

**Comment by abhishekabhi789** [comment]
Hi, I just updated the apk in the release, https://github.com/abhishekabhi789/LyricsForPowerAmp/releases/tag/v1.1
can you try this?

**Comment by Asuka-pr8** [comment]
Yeah indeed its working now
But while we are at it I also did face another crash before and in older releases too for some specific results
Sadly the only one I remember atm is when you search "magical" in coarse search and go down a couple of results it crashes
I am pretty sure it happens with other specific results too

Either way here is a log file again incase it helped before
[(2)crash-io-github-abhishekabhi789-lyricsforpoweramp-16_10-09-10-46_944.zip](https://github.com/user-attachments/files/17390909/2.crash-io-github-abhishekabhi789-lyricsforpoweramp-16_10-09-10-46_944.zip)

And lastly thanks for your hard work :D

**Comment by abhishekabhi789** [comment]
Fixed that one too, the search result contains [this track](https://lrclib.net/api/get/944499) which has only 5 lines, meanwhile app needs 6 lines to show in the card when it is collapsed.
I've re-uploaded the APK.
Thank you for reporting these issues.
