### ISSUE TITLE
What is "set dummy lyrics" option in misc settings?

### ISSUE THREAD

**Issue by lovelohar05** [abhishekabhi789/LyricsForPowerAmp#6]
Hey dev, I'm enjoying your app. Its an amazing app. I recommend you to create a documentation for this app and explain all the new features with every release. It's not that complicated but still it would be great. Hope you'll understand. Thanks 🙂

**Comment by abhishekabhi789** [comment]
Hi there,

Yes, that settings might be confusing, but I added it like a hack to launch the plugin for a manual search if it fails to fetch lyrics for the background request from PowerAmp. Thus we can search with corrected track metadata.

This part is now replaced with a notification, suggesting a manual search.

Sure, I'll either avoid such confusing terms, or explain them in the README for upcoming releases. 

Thanks for the feedback.
