### ISSUE TITLE
Option to add lyrics not showing up

### ISSUE THREAD

**Issue by Trout47** [abhishekabhi789/LyricsForPowerAmp#7]
In poweramp, when opening the lyrics in a song, it used to have an option to add the lyrics using this plug-in. Now, I'm given the screen in the screenshot I've attached. It shows that under every song that I haven't added lyrics to yet with the exception of one. I've went under the options of the app it opens but this plug-in isn't an option.

This is before: 
![Screenshot_20240804_225043_Poweramp](https://github.com/user-attachments/assets/40a8250a-166a-44cf-b19f-2c471c92082a)

This is after: 
![Screenshot_20240804_224842_Poweramp](https://github.com/user-attachments/assets/832de679-b7c8-4cb1-b431-d6272e2ac464)

**Comment by abhishekabhi789** [comment]
I've removed the 'Setting Dummy Lyrics' behavior with [v1.0](https://github.com/abhishekabhi789/LyricsForPowerAmp/releases/tag/v1.0). Now the plugin app will post a notification when there are no matching results for the automatic request from Poweramp.

Make sure you have enabled the `Show lyrics request notification` under the "Misc" category in plugin settings to receive notifications. Upon clicking the notification, you'll be taken to the search input page with track metadata typed in the input field.
If this option is disabled, the plugin won't post the notification when it fails to find a matching result, and you can't perform a manual search.
Also, check under Android settings to ensure you haven't accidentally blocked notifications from this plugin.
The reason for removing the 'Dummy Lyrics' approach is that it marks tracks as having lyrics in the Poweramp UI, though it's merely a placeholder to start a manual search.
If you have any further queries, please reopen this issue.
