### ISSUE TITLE
[Enhancement] Option to add lyrics directly into lyrics metadata tag.

### ISSUE THREAD

**Issue by confident-hate** [abhishekabhi789/LyricsForPowerAmp#8]
Hi, Thanks for this beautiful app.

It would be great if this app can directly edit metadata tag of the music file. 

As poweramp checks if the music file contains this tag and display it in lyrics section.

It can also help when we accidentally selected wrong lyrics. We can directly edit this tag manually via any file manager and try to re-search via plugin.

**Comment by abhishekabhi789** [comment]
Thank you for the feedback, I've already tried to do so by sending the metadata provided by the lyrics API to Poweramp along with lyrics, however Poweramp ignores this metadata and takes only the lyrics. As of now, the plugin app doesn't have storage access, so it can't really edit any file properties. The lyrics sent by the plugin is even stored in Poweramp cache. 
 
There are several projects out there that can help you fix metadata tags in better ways, such as this https://github.com/BobbyESP/Metadator project. 
 
If the lyrics you have selected are incorrect, you will still be able to access the search window by clicking the >> icon located within the Poweramp lyrics window.
