### ISSUE TITLE
how do we use this plugin?

### ISSUE THREAD

**Issue by punzme** [abhishekabhi789/LyricsForPowerAmp#9]
okay, i am actually confused with this plugin because there is no documentation. do we need to choose this plugin in power amp setting - lyric- 3rd party plugin?, because this app name not showing in the plugin selection selection. And of course no notif since there is no lyric found.
edit: okat actually i am the stupid one, i need to adjust the notification setting and allow it on my firewall since i am using custom rom.

**Comment by abhishekabhi789** [comment]
Fine, no problem. Closing this issue as it is solved.
